version: '3'
services:
  api:
    image: 'node:12.18.4'
    working_dir: /code
    ports:
      - 3000:3000
    environment: 
      - PORT=3000
      - PGUSER=futureproof
      - PGHOST=db
      - PGPASSWORD=habitpass
      - PGDATABASE=habits
      - PGPORT=5432
    depends_on: 
      - db
    volumes:
      - type: bind
        source: ./
        target: /code
    command: bash -c "npm install && npm run startDev"
  db:
    image: 'postgres:11.1'
    expose:
      - "5432"
    volumes:
      - "dbdata:/var/lib/postgresql/data"
      - "./db/:/docker-entrypoint-initdb.d/:ro"
    environment: 
      - POSTGRES_DB=habits
      - POSTGRES_USER=futureproof
      - POSTGRES_PASSWORD=habitpass

volumes:
  dbdata: