version: '3'
services:
  api:
    image: 'node:12.18.4'
    working_dir: /code
    volumes:
      - type: bind
        source: ./
        target: /code
  db:
    image: 'postgres:11.1'
    volumes:
      - "./db/:/docker-entrypoint-initdb.d/:ro"
    environment: 
      - POSTGRES_USER=futureproof