services:
  api:
    container_name: habit_test_api
    environment: 
      - PGUSER=futureproof
      - PGHOST=db
      - PGPASSWORD=habitpass
      - PGDATABASE=habit_test
      - PGPORT=5432
      - NODE_ENV=test
    depends_on:
      - db
    tty: true
  db:
    container_name: habit_test_db
    volumes:
      - "test_db:/var/lib/postgresql/data"
    environment: 
      - POSTGRES_DB=habit_test
      - POSTGRES_PASSWORD=habitpass
volumes:
  test_db:
networks: 
  default:
    name: habit_app_test